### ISSUE TITLE
Procrastinate: random mouse movements

### ISSUE THREAD

**Issue by clouedoc** [anonimoconiglio/puppeteer-helper#2]
Some antibot services such as Akamai look at mouse movements to detect bots.
I believe that your `procrastinate` function would benefit from adding mouse movements using, e.g., the `ghost-cursor` package.

It is worth mentioning that mouse movements must come from CDP; otherwise they won't be marked as trusted.

**Comment by fsgreco** [comment]
Thank you very much for this feedback! (and sorry for the late response)
I'll try to implement this, indeed I was thinking that also the mouse scrolling could be done by simulating the actual mouse scrolling. 

PS: may I ask you to explain better what do you mean with "movements must come from CDP"?

**Comment by clouedoc** [comment]
>sorry for the late response

Don't worry, it was just feedback for your own knowledge 🙂 

>PS: may I ask you to explain better what do you mean with "movements must come from CDP"?

You can emulate mouse movements straight from JavaScript, but the events that it generates will be market as untrusted.
To avoid this problem, you need to use a [CDP method](https://chromedevtools.github.io/devtools-protocol/tot/)

**Comment by fsgreco** [comment]
Thanks again! I'll look into it!

**Comment by fsgreco** [comment]
So I digged into this issue. 

I tried to recreate a simple mouse movement directly inside the function (the idea was to avoid adding `ghost-cursor` as a dependency). 

But then, while reading the source code of Puppeteer I discovered that it already uses a _CDPSession_ for its out of the box method `page.mouse.move()` -  [source code here][puppeteeer-move-src] -  (it sends a native a `Input.dispatchMouseEvent` as event). So it seems to me that by using it the movement already come from CDP method.

Let me know if I'm missing something here! 

In the meantime I merged a pull request with the addition of a simple move method to `procrastinate` function. 

[puppeteeer-move-src]: https://github.com/puppeteer/puppeteer/blob/a919d18ea725e5ac87755b253629774cb181ef8e/packages/puppeteer-core/src/common/Input.ts#L446

**Comment by clouedoc** [comment]
The difference with Puppeteer's implementation and ghost-cursor is that the latter uses a Bézier curve to compute intermediate mouse positions, while Puppeteer uses a simple linear function.

I don't know how important this is, since I've personally settled on ghost-cursor for my human-like mouse movements needs a long time ago 🙂.

But since there is definitely a horizon on Bézier curves (they could easily be detected by anti-bots), linear "curves" seem even more at risk of detection.

**Comment by fsgreco** [comment]
Thanks, will dig into it in the future. I was also thinking to expand the main function in order to let the user choose to use a session with the plugin puppeteer-stealth. But that will need a refactor for sure.
